Algoritmo "Exercio 6.6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que calcula a área do hexágono.
// Autor(a)    : Giovana
// Data atual  : 23/03/2025
Var

   lado, area: real

Inicio

   escreva("Digite o valor do lado do hexágono: ")
   leia(lado)

   area <- (3 * raizq(3) / 2) * (lado ^ 2)

   escreval("A área do hexágono é: ", area)

Fimalgoritmo