Algoritmo "Exercicio 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que escreve o valor do numero antecessor digitado
// Autor(a)    : Giovana
// Data atual  : 23/03/2025
Var

   numero, antecessor: inteiro

Inicio

   escreval("Digite um número: ")
   leia(numero)
   antecessor <- numero - 1
   escreval("O antecessor de ", numero, " é ", antecessor)

Fimalgoritmo