Algoritmo "EXERCICIO 12"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Converte Fahrenheit em Celsius
// Autor(a)    : Giovana
// Data atual  : 23/03/2025
Var

   Fahrenheit, Celsius: real

Inicio

   escreval("Digite a temperatura em Fahrenheit:")
   leia(Fahrenheit)
   
   Celsius <- (Fahrenheit - 32) * 5 / 9
   escreval ("Celsius é igual a: ", Celsius)

Fimalgoritmo