Algoritmo "Exercio 6.5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que calcula a área do losangulo.
// Autor(a)    : Giovana
// Data atual  : 23/03/2025
Var

   base, altura, area: real

Inicio

   escreval("Digite o valor da base do losangulo: ")
   leia (base)
   escreval("Digite o valor da altura do losangulo: ")
   leia (altura)
   area <- (base * altura) / 2
   escreval("A área do losangulo é: ", area)

Fimalgoritmo