Algoritmo "Exercio 6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que calcula a área do triangulo.
// Autor(a)    : Giovana
// Data atual  : 23/03/2025
Var

   base, altura, area: real

Inicio

   escreval("Digite a base do triângulo: ")
   leia (base)
   escreval("Digite a altura do triângulo: ")
   leia (altura)
   area <- (base * altura) / 2
   escreval("A área do triângulo é: ", area)

Fimalgoritmo