Algoritmo "Exercio 6.3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que calcula a área do retângulo.
// Autor(a)    : Giovana
// Data atual  : 23/03/2025
Var

   base, altura, area: real

Inicio

   escreval("Digite a base do retângulo: ")
   leia (base)
   escreval("Digite a altura do retângulo: ")
   leia (altura)
   area <- (base * altura) / 2
   escreval("A área do retângulo é: ", area)

Fimalgoritmo