Algoritmo "L03A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Tabuada
// Autor(a)    : Giovana
// Data atual  : 14/04/2025
Var
// Seção de Declarações das variáveis 

   i, numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Digite um numero: ")
   leia(numero)
   
   Enquanto i <= 10 faça
        Escreval(numero, " x ", i, " = ", numero * i)
        i <- i + 1
    Fimenquanto

Fimalgoritmo