Algoritmo "L03D"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Numeros inteiros ímpares na faixa de 0 a 20.
// Autor(a)    : Giovana
// Data atual  : 14/04/2025
Var
   // Seção de Declarações das variáveis

   i, soma: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   i <- 1

   enquanto i <= 20 faca
      se i % 2 <> 0 entao
         escreval(i)
      fimse
      i <- i + 1
   fimenquanto


Fimalgoritmo