Algoritmo "L05E"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Programa que apresenta todos os valores numéricos inteiros ímpares entre 0 a 20.
// Autor(a)    : Giovana
// Data atual  : 15/04/2025
Var
   // Seção de Declarações das variáveis

   i : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para i de 0 até 20 faça
      se (i % 2 <> 0) entao
         escreval(i)
      fimse
   fimpara

Fimalgoritmo