Algoritmo "L05F"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Programa que apresenta todos os números divisíveis por 4 que sejam menores que 200.
// Autor(a)    : Giovana
// Data atual  : 15/04/2025
Var
   // Seção de Declarações das variáveis

   i : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para i de 1 até 199 faça
      se (i % 4 = 0) entao
         escreval(i)
      fimse
   fimpara

Fimalgoritmo