Algoritmo "Contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Contador de 1 a 10
// Autor(a)    : Giovana
// Data atual  : 07/04/2025
Var
   // Seção de Declarações das variáveis

   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Contador de 1 a 10")
   
   contador <- 1
   repita
      escreval(contador)
      contador <- contador + 1
   até (contador > 10)

Fimalgoritmo